ALTER TABLE "Satuan"
ADD COLUMN "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "Supplier"
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "Material" ADD COLUMN "UpdatedBy" TEXT;
ALTER TABLE "FinishGood" ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "BoxQTY"
ADD COLUMN "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "ManPower"
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "EmailNotification"
ADD COLUMN "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "DisplayConfig"
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "PrinterSetting"
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "MTCUserManagement"
ADD COLUMN "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "CreatedBy" TEXT,
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

ALTER TABLE "ApiKey"
ADD COLUMN "UpdatedAt" TIMESTAMP(3),
ADD COLUMN "UpdatedBy" TEXT;

UPDATE "Satuan" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "Supplier" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "Material" SET "UpdatedBy" = 'SYSTEM';
UPDATE "FinishGood" SET "UpdatedBy" = 'SYSTEM';
UPDATE "BoxQTY" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "ManPower" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "EmailNotification" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "DisplayConfig" SET "CreatedAt" = CURRENT_TIMESTAMP WHERE "CreatedAt" IS NULL;
UPDATE "DisplayConfig" SET "CreatedBy" = 'SYSTEM', "UpdatedBy" = 'SYSTEM';
UPDATE "PrinterSetting" SET "CreatedBy" = 'SYSTEM', "UpdatedBy" = 'SYSTEM';
UPDATE "MTCUserManagement" SET "CreatedBy" = 'SYSTEM', "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "ApiKey" SET "UpdatedAt" = CURRENT_TIMESTAMP, "UpdatedBy" = 'SYSTEM';
UPDATE "MTCRole" SET "CreateBy" = 'SYSTEM' WHERE "CreateBy" IS NULL;
UPDATE "MTCRole" SET "UpdateDate" = COALESCE("UpdateDate", "CreateDate", CURRENT_TIMESTAMP), "UpdateBy" = 'SYSTEM' WHERE "UpdateDate" IS NULL OR "UpdateBy" IS NULL;
UPDATE "MTCPermission" SET "CreateBy" = 'SYSTEM' WHERE "CreateBy" IS NULL;
UPDATE "MTCPermission" SET "UpdateDate" = COALESCE("UpdateDate", "CreateDate", CURRENT_TIMESTAMP), "UpdateBy" = 'SYSTEM' WHERE "UpdateDate" IS NULL OR "UpdateBy" IS NULL;

ALTER TABLE "Satuan" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "Supplier" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "Material" ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "FinishGood" ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "BoxQTY" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "ManPower" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "EmailNotification" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "DisplayConfig" ALTER COLUMN "CreatedAt" SET NOT NULL, ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "PrinterSetting" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "MTCUserManagement" ALTER COLUMN "CreatedBy" SET NOT NULL, ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "ApiKey" ALTER COLUMN "UpdatedAt" SET NOT NULL, ALTER COLUMN "UpdatedBy" SET NOT NULL;
ALTER TABLE "MTCRole" ALTER COLUMN "CreateBy" SET NOT NULL, ALTER COLUMN "UpdateDate" SET NOT NULL, ALTER COLUMN "UpdateBy" SET NOT NULL;
ALTER TABLE "MTCPermission" ALTER COLUMN "CreateBy" SET NOT NULL, ALTER COLUMN "UpdateDate" SET NOT NULL, ALTER COLUMN "UpdateBy" SET NOT NULL;
