import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { LogProcessService } from '../common/log-process/log-process.service';
import { Workbook } from 'exceljs';
import dayjs from 'dayjs';
import type { LogProcessModel } from '../generated/prisma/models';
import {
  ItemCategory,
  LocationType,
  TransactionType,
} from '../generated/prisma/enums';

@Injectable()
export class ReportService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly logService: LogProcessService,
  ) {}

  private parseDateDDMMYYYY(dateStr: string): Date {
    const day = dateStr.substring(0, 2);
    const month = dateStr.substring(2, 4);
    const year = dateStr.substring(4, 8);
    return new Date(year + '-' + month + '-' + day);
  }

  private formatDate(date: Date | string | null | undefined): string {
    if (!date) return '-';
    return dayjs(date).format('DD/MM/YYYY HH:mm');
  }

  private formatDateFull(date: Date | string | null | undefined): string {
    if (!date) return '-';
    return dayjs(date).format('DD MMMM YYYY HH:mm:ss');
  }

  private getHeaderFill() {
    return {
      type: 'pattern' as const,
      pattern: 'solid' as const,
      fgColor: { argb: '1F4E79' },
    };
  }

  private getWhiteFill() {
    return {
      type: 'pattern' as const,
      pattern: 'solid' as const,
      fgColor: { argb: 'FFFFFF' },
    };
  }

  private getGrayFill() {
    return {
      type: 'pattern' as const,
      pattern: 'solid' as const,
      fgColor: { argb: 'F2F2F2' },
    };
  }

  private getSummaryFill() {
    return {
      type: 'pattern' as const,
      pattern: 'solid' as const,
      fgColor: { argb: 'D6DCE5' },
    };
  }

  private getThinBorder() {
    return {
      top: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
      bottom: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
      left: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
      right: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
    };
  }

  private getHeaderBorder() {
    return {
      top: { style: 'thin' as const, color: { argb: '000000' } },
      bottom: { style: 'thin' as const, color: { argb: '000000' } },
      left: { style: 'thin' as const, color: { argb: '000000' } },
      right: { style: 'thin' as const, color: { argb: '000000' } },
    };
  }

  private createWorkbook(
    worksheetTitle: string,
    columnWidths: number[],
  ): { workbook: Workbook; worksheet: any } {
    const workbook = new Workbook();
    workbook.creator = 'ANSEI API System';
    workbook.created = new Date();

    const worksheet = workbook.addWorksheet(worksheetTitle, {
      pageSetup: {
        paperSize: 9,
        orientation: 'landscape' as const,
        horizontalDpi: 300,
        verticalDpi: 300,
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        margins: {
          top: 0.5,
          bottom: 0.5,
          left: 0.5,
          right: 0.5,
          header: 0.3,
          footer: 0.3,
        },
      },
      headerFooter: {
        firstHeader: '&"Calibri,Bold"&14ANSEI Production System',
        firstFooter: '&"Calibri"&10Page &P of &N',
        oddFooter:
          '&"Calibri"&10Page &P of &N | Generated by ANSEI System at &D',
      },
    });

    columnWidths.forEach((width, index) => {
      worksheet.getColumn(index + 1).width = width;
    });

    return { workbook, worksheet };
  }

  private setupReportHeader(
    worksheet: any,
    reportTitle: string,
    colCount: number,
    fromDate?: string,
    toDate?: string,
  ): void {
    const lastCol =
      worksheet.getColumn(colCount).letter ||
      String.fromCharCode(64 + colCount);
    worksheet.addRow([]);
    worksheet.mergeCells('A2:' + lastCol + '2');
    const titleCell = worksheet.getCell('A2');
    titleCell.value = reportTitle;
    titleCell.font = {
      name: 'Calibri',
      size: 18,
      bold: true,
      color: { argb: '1F4E79' },
    };
    titleCell.alignment = {
      horizontal: 'center' as const,
      vertical: 'middle' as const,
    };
    worksheet.mergeCells('A3:' + lastCol + '3');
    const subtitleCell = worksheet.getCell('A3');
    const fromFormatted = fromDate
      ? fromDate.substring(0, 2) +
        '/' +
        fromDate.substring(2, 4) +
        '/' +
        fromDate.substring(4, 8)
      : '-';
    const toFormatted = toDate
      ? toDate.substring(0, 2) +
        '/' +
        toDate.substring(2, 4) +
        '/' +
        toDate.substring(4, 8)
      : '-';
    subtitleCell.value =
      'Period: ' +
      fromFormatted +
      ' to ' +
      toFormatted +
      ' | Generated: ' +
      this.formatDateFull(new Date()) +
      ' | ANSEI Production System';
    subtitleCell.font = {
      name: 'Calibri',
      size: 11,
      color: { argb: '666666' },
    };
    subtitleCell.alignment = {
      horizontal: 'center' as const,
      vertical: 'middle' as const,
    };
    worksheet.addRow([]);
  }

  private addColumnHeaders(worksheet: any, headers: string[]): any {
    const headerRow = worksheet.addRow(headers);
    headerRow.height = 30;
    const headerFill = this.getHeaderFill();
    const headerBorder = this.getHeaderBorder();
    headerRow.eachCell((cell: any) => {
      cell.font = {
        name: 'Calibri',
        size: 11,
        bold: true,
        color: { argb: 'FFFFFF' },
      };
      cell.fill = headerFill;
      cell.alignment = {
        horizontal: 'center' as const,
        vertical: 'middle' as const,
        wrapText: true,
      };
      cell.border = headerBorder;
    });
    return headerRow;
  }

  private addDataRow(
    worksheet: any,
    values: any[],
    rowIndex: number,
    numberColumns: number[] = [],
  ): void {
    const row = worksheet.addRow(values);
    row.height = 20;
    const isEven = rowIndex % 2 === 0;
    const fill = isEven ? this.getGrayFill() : this.getWhiteFill();
    const thinBorder = this.getThinBorder();
    row.eachCell((cell: any, colNumber: number) => {
      cell.font = { name: 'Calibri', size: 10 };
      cell.fill = fill;
      cell.border = thinBorder;
      if (numberColumns.includes(colNumber)) {
        cell.alignment = {
          horizontal: 'right' as const,
          vertical: 'middle' as const,
        };
      } else if (colNumber === 1) {
        cell.alignment = {
          horizontal: 'center' as const,
          vertical: 'middle' as const,
        };
      } else {
        cell.alignment = {
          horizontal: 'left' as const,
          vertical: 'middle' as const,
        };
      }
    });
  }

  private addSummaryRow(
    worksheet: any,
    values: any[],
    numberColumns: number[],
  ): void {
    const row = worksheet.addRow(values);
    row.height = 25;
    const summaryFill = this.getSummaryFill();
    row.eachCell((cell: any) => {
      cell.font = { name: 'Calibri', size: 11, bold: true };
      cell.fill = summaryFill;
      cell.border = {
        top: { style: 'medium' as const, color: { argb: '1F4E79' } },
        bottom: { style: 'medium' as const, color: { argb: '1F4E79' } },
        left: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
        right: { style: 'thin' as const, color: { argb: 'CCCCCC' } },
      };
    });
  }

  private finalizeWorksheet(worksheet: any, dataRowCount: number): void {
    if (dataRowCount > 0) {
      worksheet.views = [
        { state: 'frozen' as const, xSplit: 0, ySplit: 5, activeCell: 'A6' },
      ];
      const colCount = worksheet.columnCount || 10;
      worksheet.autoFilter = {
        from: { row: 5, column: 1 },
        to: { row: 5, column: colCount },
      };
    }
  }

  private async writeBuffer(workbook: Workbook): Promise<Buffer> {
    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer as any);
  }

  // ==================== REPORT GENERATORS ====================

  async generateStockMaterialReport(): Promise<Buffer> {
    const colWidths = [6, 18, 30, 20, 15, 10, 12, 14, 12];
    const { workbook, worksheet } = this.createWorkbook(
      'Stock Material',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'STOCK MATERIAL REPORT',
      colWidths.length,
    );
    const headers = [
      'No.',
      'Part Number',
      'Part Name',
      'Supplier',
      'Rack Location',
      'Satuan',
      'Qty Rack',
      'Qty Warehouse',
      'Total Stock',
    ];
    this.addColumnHeaders(worksheet, headers);
    const materials = await this.prisma.material.findMany({
      where: { IsActive: true },
      include: { SatuanData: true },
      orderBy: { PartNumber: 'asc' },
    });
    let grandTotalRack = 0,
      grandTotalWarehouse = 0;
    materials.forEach((m, index) => {
      const qtyRack = m.QtyRack || 0,
        qtyWarehouse = m.QtyWarehouse || 0;
      grandTotalRack += qtyRack;
      grandTotalWarehouse += qtyWarehouse;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          m.PartNumber,
          m.PartName,
          m.Supplier || '-',
          m.RackLocation || '-',
          m.SatuanData?.Name || '-',
          qtyRack,
          qtyWarehouse,
          qtyRack + qtyWarehouse,
        ],
        index,
        [7, 8, 9],
      );
    });
    this.addSummaryRow(
      worksheet,
      [
        '',
        '',
        '',
        '',
        '',
        'GRAND TOTAL',
        grandTotalRack,
        grandTotalWarehouse,
        grandTotalRack + grandTotalWarehouse,
      ],
      [7, 8, 9],
    );
    this.finalizeWorksheet(worksheet, materials.length);
    return this.writeBuffer(workbook);
  }

  async generateIncomingWarehouseReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 18, 18, 22, 18, 18, 18, 28, 12, 12];
    const { workbook, worksheet } = this.createWorkbook(
      'Incoming Warehouse',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'INCOMING WAREHOUSE REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Incoming ID',
      'PO Number',
      'Supplier Name',
      'Received Date',
      'Received By',
      'Part Number',
      'Part Name',
      'Qty Ordered',
      'Qty Checked',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const incomings = await this.prisma.incoming.findMany({
      where: whereClause,
      include: {
        SupplierData: true,
        IncomingMaterial: { include: { MaterialData: true } },
      },
      orderBy: { CreatedAt: 'desc' },
    });
    const data: any[] = [];
    incomings.forEach((incoming) => {
      if (incoming.IncomingMaterial.length === 0) {
        data.push({
          incomingId: incoming.Id,
          poId: incoming.PoId,
          supplierName: incoming.SupplierData?.Name || '-',
          createdAt: incoming.CreatedAt,
          receivedBy: incoming.ReceivedBy,
          partNumber: '-',
          partName: '-',
          qty: 0,
          qtyChecked: 0,
        });
      } else {
        incoming.IncomingMaterial.forEach((mat) => {
          data.push({
            incomingId: incoming.Id,
            poId: incoming.PoId,
            supplierName: incoming.SupplierData?.Name || '-',
            createdAt: incoming.CreatedAt,
            receivedBy: incoming.ReceivedBy,
            partNumber: mat.MaterialData?.PartNumber || mat.MaterialId,
            partName: mat.MaterialData?.PartName || '-',
            qty: mat.Qty,
            qtyChecked: mat.QtyChecked,
          });
        });
      }
    });
    let grandTotalQty = 0,
      grandTotalChecked = 0;
    data.forEach((row, index) => {
      grandTotalQty += row.qty;
      grandTotalChecked += row.qtyChecked;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          row.incomingId,
          row.poId,
          row.supplierName,
          this.formatDate(row.createdAt),
          row.receivedBy,
          row.partNumber,
          row.partName,
          row.qty,
          row.qtyChecked,
        ],
        index,
        [9, 10],
      );
    });
    this.addSummaryRow(
      worksheet,
      ['', '', '', '', '', '', '', '', 'GRAND TOTAL', grandTotalChecked],
      [9, 10],
    );
    this.finalizeWorksheet(worksheet, data.length);
    return this.writeBuffer(workbook);
  }

  async generateIncomingRackReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 22, 18, 18, 28, 20, 14, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Incoming Rack',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'INCOMING RACK REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Reference Doc',
      'Transfer Date',
      'Part Number',
      'Part Name',
      'Supplier',
      'Qty Transferred',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {
      ItemCategory: ItemCategory.MATERIAL,
      Location: LocationType.RACK,
      TransactionType: TransactionType.TRANSFER_TO_RACK,
    };
    if (fromdate || todate) {
      whereClause.TransactionDate = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.TransactionDate.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.TransactionDate.lte = to;
      }
    }
    const ledgers = await this.prisma.inventoryLedger.findMany({
      where: whereClause,
      include: { MaterialData: true },
      orderBy: { TransactionDate: 'desc' },
    });
    let grandTotalQty = 0;
    ledgers.forEach((ledger, index) => {
      grandTotalQty += ledger.QtyIn || 0;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          ledger.ReferenceDoc || '-',
          this.formatDate(ledger.TransactionDate),
          ledger.MaterialId,
          ledger.MaterialData?.PartName || '-',
          ledger.MaterialData?.Supplier || '-',
          ledger.QtyIn || 0,
          ledger.CreatedBy,
        ],
        index,
        [7],
      );
    });
    this.addSummaryRow(
      worksheet,
      ['', '', '', '', '', '', 'GRAND TOTAL', grandTotalQty],
      [7],
    );
    this.finalizeWorksheet(worksheet, ledgers.length);
    return this.writeBuffer(workbook);
  }

  async generateTransferMaterialReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 22, 22, 12, 18, 18, 18, 18, 18, 28, 12, 12, 12];
    const { workbook, worksheet } = this.createWorkbook(
      'Transfer Material',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'TRANSFER MATERIAL REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'DN Number',
      'Destination',
      'Status',
      'Created Date',
      'Created By',
      'Shipped Date',
      'Shipped By',
      'Part Number',
      'Part Name',
      'Qty Requested',
      'Qty Picking',
      'Qty Received',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const deliveryNotes = await this.prisma.materialDeliveryNote.findMany({
      where: whereClause,
      include: { Details: { include: { MaterialData: true } } },
      orderBy: { CreatedAt: 'desc' },
    });
    const data: any[] = [];
    deliveryNotes.forEach((dn) => {
      if (dn.Details.length === 0) {
        data.push({ dn, detail: null });
      } else {
        dn.Details.forEach((detail) => {
          data.push({ dn, detail });
        });
      }
    });
    let grandTotalRequested = 0,
      grandTotalPicking = 0,
      grandTotalReceived = 0;
    data.forEach((item, index) => {
      const { dn, detail } = item;
      const qtyReq = detail?.QtyRequested || 0,
        qtyPick = detail?.QtyPicking || 0,
        qtyRecv = detail?.QtyReceived || 0;
      grandTotalRequested += qtyReq;
      grandTotalPicking += qtyPick;
      grandTotalReceived += qtyRecv;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          dn.DeliveryNoteNum,
          dn.Destination,
          dn.Status,
          this.formatDate(dn.CreatedAt),
          dn.CreatedBy,
          this.formatDate(dn.ShippedAt),
          dn.ShippedBy || '-',
          detail ? detail.MaterialData?.PartNumber || detail.MaterialId : '-',
          detail ? detail.MaterialData?.PartName || '-' : '-',
          qtyReq,
          qtyPick,
          qtyRecv,
        ],
        index,
        [11, 12, 13],
      );
    });
    this.addSummaryRow(
      worksheet,
      [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'GRAND TOTAL',
        grandTotalPicking,
        grandTotalReceived,
      ],
      [11, 12, 13],
    );
    this.finalizeWorksheet(worksheet, data.length);
    return this.writeBuffer(workbook);
  }

  async generateProductionReleaseReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 18, 18, 12, 12, 12, 10, 18, 18, 18, 18, 28, 12];
    const { workbook, worksheet } = this.createWorkbook(
      'Production Release',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'PRODUCTION RELEASE RESUME REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Release Number',
      'Plan Date',
      'Status',
      'Total Target',
      'Total Good',
      'Total NG',
      'Created Date',
      'Created By',
      'PO Number',
      'FG Part Number',
      'FG Part Name',
      'Forecast Qty',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.PlanDate = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.PlanDate.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.PlanDate.lte = to;
      }
    }
    const releases = await this.prisma.productionRelease.findMany({
      where: whereClause,
      include: { Forecasts: { include: { PartData: true } } },
      orderBy: { PlanDate: 'desc' },
    });
    const data: any[] = [];
    releases.forEach((release) => {
      if (release.Forecasts.length === 0) {
        data.push({ release, forecast: null });
      } else {
        release.Forecasts.forEach((forecast) => {
          data.push({ release, forecast });
        });
      }
    });
    data.forEach((item, index) => {
      const { release, forecast } = item;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          release.ReleaseNumber,
          this.formatDate(release.PlanDate),
          release.Status,
          release.TotalTargetQty,
          release.TotalGoodQty,
          release.TotalNgQty,
          this.formatDate(release.CreatedAt),
          release.CreatedBy,
          forecast ? forecast.PoId : '-',
          forecast
            ? forecast.PartData?.PartNumber || forecast.FinishGoodId
            : '-',
          forecast ? forecast.PartData?.PartName || '-' : '-',
          forecast ? forecast.Qty : 0,
        ],
        index,
        [5, 6, 7, 13],
      );
    });
    this.finalizeWorksheet(worksheet, data.length);
    return this.writeBuffer(workbook);
  }

  async generatePokayokeScanReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 18, 18, 18, 28, 10, 18, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Pokayoke Scan',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'POKAYOKE SCAN HISTORY REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Label Number',
      'PO Number',
      'Part Number',
      'Part Name',
      'Status',
      'Scan Date',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const scans = await this.prisma.pokayokeScanHistory.findMany({
      where: whereClause,
      orderBy: { CreatedAt: 'desc' },
    });
    scans.forEach((scan, index) => {
      this.addDataRow(
        worksheet,
        [
          index + 1,
          scan.LabelNumber,
          scan.PoId,
          scan.PartNumber,
          scan.PartName,
          scan.Status,
          this.formatDate(scan.CreatedAt),
          scan.CreatedBy,
        ],
        index,
      );
    });
    this.finalizeWorksheet(worksheet, scans.length);
    return this.writeBuffer(workbook);
  }

  async generateDeliveryHistoryReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 18, 18, 18, 28, 10, 18, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Delivery History',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'DELIVERY HISTORY REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'PO Number',
      'Label Number',
      'FG Part Number',
      'FG Part Name',
      'Qty',
      'Delivery Date',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const deliveries = await this.prisma.deliveryHistory.findMany({
      where: whereClause,
      include: { PoData: { include: { PartData: true } }, LabelData: true },
      orderBy: { CreatedAt: 'desc' },
    });
    let grandTotalQty = 0;
    deliveries.forEach((d, index) => {
      grandTotalQty += d.Qty;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          d.ForecastId,
          d.LabelData?.LabelNumber || d.LabelDataId,
          d.LabelData?.FinishGoodId || '-',
          d.PoData?.PartData?.PartName || '-',
          d.Qty,
          this.formatDate(d.CreatedAt),
          d.CreatedBy,
        ],
        index,
        [6],
      );
    });
    this.addSummaryRow(
      worksheet,
      ['', '', '', '', 'GRAND TOTAL', grandTotalQty, '', ''],
      [6],
    );
    this.finalizeWorksheet(worksheet, deliveries.length);
    return this.writeBuffer(workbook);
  }

  async generateProductionReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 12, 10, 18, 18, 28, 18, 10, 10, 10, 12, 18, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Production Report',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'PRODUCTION REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Date',
      'Time',
      'PO Number',
      'FG Part Number',
      'FG Part Name',
      'Operator',
      'Qty',
      'NG Qty',
      'Good Qty',
      'Stop Minutes',
      'Created At',
      'Validated At',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.ProductionStamp = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.ProductionStamp.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.ProductionStamp.lte = to;
      }
    }
    const reports = await this.prisma.productionReport.findMany({
      where: whereClause,
      include: { FGData: true, ManPowerData: true },
      orderBy: { ProductionStamp: 'desc' },
    });
    reports.forEach((r, index) => {
      this.addDataRow(
        worksheet,
        [
          index + 1,
          r.Date || '-',
          r.Time || '-',
          r.PoNumber || '-',
          r.FGData?.PartNumber || r.FinishGoodId,
          r.FGData?.PartName || '-',
          r.ManPowerData?.Name || '-',
          r.Qty,
          r.NgQty,
          r.Qty - r.NgQty,
          r.StopMinute || 0,
          this.formatDate(r.CreatedAt),
          r.ValidatedAt ? this.formatDate(r.ValidatedAt) : '-',
        ],
        index,
        [8, 9, 10, 11],
      );
    });
    this.finalizeWorksheet(worksheet, reports.length);
    return this.writeBuffer(workbook);
  }

  async generateShoppingHistoryReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 22, 18, 18, 28, 12, 12, 18, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Shopping History',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'SHOPPING HISTORY REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'ID',
      'PO Number',
      'Material Part Number',
      'Material Part Name',
      'Type',
      'Qty Pick',
      'Created At',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const shoppings = await this.prisma.shopping.findMany({
      where: whereClause,
      include: { MaterialData: true, ForecastData: true },
      orderBy: { CreatedAt: 'desc' },
    });
    let grandTotalQty = 0;
    shoppings.forEach((s, index) => {
      grandTotalQty += s.QtyPick;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          s.Id,
          s.ForecastData?.PoId || s.ForecastId || '-',
          s.MaterialData?.PartNumber || s.MaterialId,
          s.MaterialData?.PartName || '-',
          s.Type,
          s.QtyPick,
          this.formatDate(s.CreatedAt),
          s.CreatedBy,
        ],
        index,
        [7],
      );
    });
    this.addSummaryRow(
      worksheet,
      ['', '', '', '', '', 'GRAND TOTAL', grandTotalQty, '', ''],
      [7],
    );
    this.finalizeWorksheet(worksheet, shoppings.length);
    return this.writeBuffer(workbook);
  }

  async generateMaterialNgReport(
    fromdate?: string,
    todate?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 10, 18, 28, 10, 35, 18, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Material NG',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'MATERIAL NG REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'ID',
      'Material Part Number',
      'Material Part Name',
      'Qty',
      'Description',
      'Created At',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.CreatedAt = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.CreatedAt.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.CreatedAt.lte = to;
      }
    }
    const materialNgs = await this.prisma.materialNG.findMany({
      where: whereClause,
      include: { MaterialData: true },
      orderBy: { CreatedAt: 'desc' },
    });
    let grandTotalQty = 0;
    materialNgs.forEach((m, index) => {
      grandTotalQty += m.Qty;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          m.Id,
          m.MaterialData?.PartNumber || m.MaterialId,
          m.MaterialData?.PartName || '-',
          m.Qty,
          m.Description,
          this.formatDate(m.CreatedAt),
          m.CreatedBy,
        ],
        index,
        [5],
      );
    });
    this.addSummaryRow(
      worksheet,
      ['', '', '', 'GRAND TOTAL', grandTotalQty, '', '', ''],
      [5],
    );
    this.finalizeWorksheet(worksheet, materialNgs.length);
    return this.writeBuffer(workbook);
  }

  async generateInventoryLedgerReport(
    fromdate?: string,
    todate?: string,
    category?: string,
    location?: string,
  ): Promise<Buffer> {
    const colWidths = [6, 18, 14, 18, 18, 16, 20, 22, 14, 12, 12, 14, 30, 18];
    const { workbook, worksheet } = this.createWorkbook(
      'Inventory Ledger',
      colWidths,
    );
    this.setupReportHeader(
      worksheet,
      'INVENTORY LEDGER REPORT',
      colWidths.length,
      fromdate,
      todate,
    );
    const headers = [
      'No.',
      'Transaction Date',
      'Item Category',
      'Material Part Number',
      'Finish Good Part Number',
      'Location',
      'Transaction Type',
      'Reference Doc',
      'Balance Before',
      'Qty In',
      'Qty Out',
      'Balance After',
      'Notes',
      'Created By',
    ];
    this.addColumnHeaders(worksheet, headers);
    const whereClause: any = {};
    if (fromdate || todate) {
      whereClause.TransactionDate = {};
      if (fromdate) {
        const from = this.parseDateDDMMYYYY(fromdate);
        from.setHours(0, 0, 0, 0);
        whereClause.TransactionDate.gte = from;
      }
      if (todate) {
        const to = this.parseDateDDMMYYYY(todate);
        to.setHours(23, 59, 59, 999);
        whereClause.TransactionDate.lte = to;
      }
    }
    if (category) whereClause.ItemCategory = category as any;
    if (location) whereClause.Location = location as any;
    const ledgers = await this.prisma.inventoryLedger.findMany({
      where: whereClause,
      include: { MaterialData: true, FGData: true },
      orderBy: { TransactionDate: 'desc' },
    });
    let grandTotalIn = 0,
      grandTotalOut = 0;
    ledgers.forEach((l, index) => {
      grandTotalIn += l.QtyIn || 0;
      grandTotalOut += l.QtyOut || 0;
      this.addDataRow(
        worksheet,
        [
          index + 1,
          this.formatDate(l.TransactionDate),
          l.ItemCategory,
          l.ItemCategory === ItemCategory.MATERIAL
            ? l.MaterialData?.PartNumber || l.MaterialId
            : '-',
          l.ItemCategory === ItemCategory.FINISH_GOOD
            ? l.FGData?.PartNumber || l.FinishGoodId
            : '-',
          l.Location,
          l.TransactionType,
          l.ReferenceDoc,
          l.BalanceBefore,
          l.QtyIn || 0,
          l.QtyOut || 0,
          l.BalanceAfter,
          l.Notes || '-',
          l.CreatedBy,
        ],
        index,
        [9, 10, 11, 12],
      );
    });
    this.addSummaryRow(
      worksheet,
      [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'GRAND TOTAL',
        '',
        grandTotalIn,
        grandTotalOut,
        '',
        '',
        '',
      ],
      [10, 11],
    );
    this.finalizeWorksheet(worksheet, ledgers.length);
    return this.writeBuffer(workbook);
  }
}
